color=${BG}
inside-color=${BG}
ring-color=${ACCENT}
line-color=${BG}
key-hl-color=${COLOR2}
bs-hl-color=${COLOR1}
separator-color=${BG}
text-color=${FG}
inside-ver-color=${BG}
ring-ver-color=${COLOR4}
text-ver-color=${FG}
inside-wrong-color=${BG}
ring-wrong-color=${COLOR1}
text-wrong-color=${FG}
inside-clear-color=${BG}
ring-clear-color=${COLOR3}
text-clear-color=${FG}
indicator-radius=90
indicator-thickness=8
font=JetBrainsMono Nerd Font
ignore-empty-password
show-failed-attempts
