set $bg #${BG}
set $fg #${FG}
set $accent #${ACCENT}
set $muted #${MUTED}
set $urgent #${COLOR1}

client.focused          $accent $accent $bg $accent $accent
client.focused_inactive $muted  $bg     $fg $muted  $muted
client.unfocused        $muted  $bg     $fg $muted  $muted
client.urgent           $urgent $urgent $bg $urgent $urgent

output * bg ${WALLPAPER}
seat seat0 xcursor_theme ${CURSOR_THEME} ${CURSOR_SIZE}
