name = "void"
family = "void"
arch = "{arch}"
package_manager = "xbps"
root = "/strata/void"
trust = "official"

[bootstrap]
method = "rootfs"
url = "https://repo-default.voidlinux.org/live/current/void-{arch}-ROOTFS-20250202.tar.xz"
sha256 = ""
strip = 0

[integration]
graphics = true
audio = true
dbus = true

[[repository]]
name = "main"
url = "https://repo-default.voidlinux.org/current"
