name = "openssh"
version = "9.8p1"
release = 1
summary = "Secure shell client and server"
license = "BSD-2-Clause"
arch = ["x86_64", "aarch64"]

[source]
url = "https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-9.8p1.tar.gz"
sha256 = "dd8bd002a379b5d499dfb050dd1fa9af8029e80461f4bb6c523c49973f5a39f3"

[build]
system = "autotools"
deps = ["gcc", "make", "openssl", "zlib"]
script = """
#!/bin/sh
./configure --prefix=/usr \\
    --sysconfdir=/etc/ssh \\
    --with-privsep-path=/var/lib/sshd \\
    --with-ssl-engine \\
    --with-zlib
make -j"$SALT_JOBS"
make DESTDIR="$SALT_DEST" install
"""

[package]
deps = ["glibc", "openssl", "zlib"]

[reproducibility]
status = "verified"
