#!/bin/bash
# saltos-install: install saltOS from the live environment to a disk.
#
# Copies the live root filesystem onto a Btrfs subvolume layout (@ @home @var
# @log @snapshots), regenerates a clean initramfs, writes fstab, and installs
# GRUB for the detected firmware (BIOS i386-pc and/or x86_64-efi). salt remains
# the package manager on the installed system.
#
# Required:
#   TARGET_DISK   block device to install onto (e.g. /dev/vda) -- ERASED
# Source of the root tree (one of):
#   SRC_SQUASHFS  path to filesystem.squashfs (unsquashed into the target)
#   SRC_ROOT      path to an already-extracted root tree (rsync'd into target)
# Optional:
#   KERNEL        path to a vmlinuz to install (else taken from SRC tree /boot)
#   HOSTNAME      target hostname (default: saltos)
#   SERIAL_CONSOLE=1  add console=ttyS0,115200 to the kernel cmdline
#   NONINTERACTIVE=1  do not prompt before erasing TARGET_DISK
set -euo pipefail

err() { echo "saltos-install: $*" >&2; exit 1; }
log() { echo "==> $*"; }

[ "$(id -u)" = 0 ] || err "must run as root"
TARGET_DISK="${TARGET_DISK:-}"
[ -n "$TARGET_DISK" ] || err "TARGET_DISK is not set"
[ -b "$TARGET_DISK" ] || err "TARGET_DISK ($TARGET_DISK) is not a block device"

SRC_SQUASHFS="${SRC_SQUASHFS:-}"
SRC_ROOT="${SRC_ROOT:-}"
if [ -z "$SRC_SQUASHFS" ] && [ -z "$SRC_ROOT" ]; then
  for c in /run/live/medium/live/filesystem.squashfs \
           /lib/live/mount/medium/live/filesystem.squashfs; do
    [ -f "$c" ] && SRC_SQUASHFS="$c" && break
  done
fi
[ -n "$SRC_SQUASHFS" ] || [ -n "$SRC_ROOT" ] || err "no SRC_SQUASHFS or SRC_ROOT"

HOSTNAME="${HOSTNAME:-saltos}"
MNT="${MNT:-/mnt/saltos-target}"

mount_opts="rw,noatime,compress=zstd:1,space_cache=v2"
rotational=1
base="$(basename "$TARGET_DISK")"
[ -r "/sys/block/$base/queue/rotational" ] && rotational="$(cat "/sys/block/$base/queue/rotational")"
[ "$rotational" = 0 ] && mount_opts="rw,noatime,compress=zstd:1,ssd,space_cache=v2,discard=async"

if [ "${NONINTERACTIVE:-0}" != 1 ]; then
  echo "This will ERASE all data on $TARGET_DISK."
  printf "Type ERASE to continue: "
  read -r ans
  [ "$ans" = "ERASE" ] || err "aborted"
fi

efi=0
[ -d /sys/firmware/efi ] && efi=1

log "partitioning $TARGET_DISK (GPT: bios-boot + ESP + btrfs)"
umount -R "$MNT" 2>/dev/null || true
wipefs -a "$TARGET_DISK" || true
sgdisk --zap-all "$TARGET_DISK"
sgdisk -n1:0:+1MiB   -t1:ef02 -c1:"BIOS boot" "$TARGET_DISK"
sgdisk -n2:0:+512MiB -t2:ef00 -c2:"EFI"       "$TARGET_DISK"
sgdisk -n3:0:0       -t3:8300 -c3:"saltOS"    "$TARGET_DISK"
partprobe "$TARGET_DISK" 2>/dev/null || true
sleep 1

part() {
  # partition node N, handling /dev/sdaN vs /dev/nvme0n1pN / loopXpN
  case "$TARGET_DISK" in
    *[0-9]) echo "${TARGET_DISK}p$1" ;;
    *)      echo "${TARGET_DISK}$1" ;;
  esac
}
ESP="$(part 2)"
ROOTP="$(part 3)"
[ -b "$ESP" ] || err "ESP $ESP did not appear"
[ -b "$ROOTP" ] || err "root partition $ROOTP did not appear"

log "creating filesystems"
mkfs.fat -F32 -n EFI "$ESP" >/dev/null
mkfs.btrfs -f -L saltOS "$ROOTP" >/dev/null

log "creating subvolumes"
mkdir -p "$MNT"
mount -o "$mount_opts" "$ROOTP" "$MNT"
for sv in @ @home @var @log @snapshots; do
  btrfs subvolume create "$MNT/$sv" >/dev/null
done
umount "$MNT"

log "mounting target"
mount -o "$mount_opts,subvol=@" "$ROOTP" "$MNT"
mkdir -p "$MNT/home" "$MNT/var" "$MNT/.snapshots" "$MNT/boot/efi"
mount -o "$mount_opts,subvol=@home" "$ROOTP" "$MNT/home"
mount -o "$mount_opts,subvol=@var" "$ROOTP" "$MNT/var"
mkdir -p "$MNT/var/log"
mount -o "$mount_opts,subvol=@log" "$ROOTP" "$MNT/var/log"
mount -o "$mount_opts,subvol=@snapshots" "$ROOTP" "$MNT/.snapshots"
mount "$ESP" "$MNT/boot/efi"

log "populating root filesystem"
if [ -n "$SRC_SQUASHFS" ]; then
  unsquashfs -f -d "$MNT" "$SRC_SQUASHFS"
else
  rsync -aHAXx --numeric-ids "$SRC_ROOT/" "$MNT/"
fi
for d in proc sys dev run tmp mnt media; do mkdir -p "$MNT/$d"; done
chmod 1777 "$MNT/tmp"

echo "$HOSTNAME" > "$MNT/etc/hostname"
sed -i 's/saltos-live/'"$HOSTNAME"'/' "$MNT/etc/hosts" 2>/dev/null || true

log "binding pseudo-filesystems for chroot"
mount --bind /dev "$MNT/dev"
mount --bind /dev/pts "$MNT/dev/pts" 2>/dev/null || true
mount -t proc proc "$MNT/proc"
mount -t sysfs sys "$MNT/sys"
mount -t tmpfs tmpfs "$MNT/run"
if [ "$efi" = 1 ]; then
  mount -t efivarfs efivarfs "$MNT/sys/firmware/efi/efivars" 2>/dev/null || true
fi
cleanup() { umount -R "$MNT" 2>/dev/null || true; }
trap cleanup EXIT

ROOT_UUID="$(blkid -s UUID -o value "$ROOTP")"
ESP_UUID="$(blkid -s UUID -o value "$ESP")"

log "writing /etc/fstab"
cat > "$MNT/etc/fstab" <<EOF
# saltOS fstab (generated by saltos-install)
UUID=$ROOT_UUID /           btrfs $mount_opts,subvol=@          0 0
UUID=$ROOT_UUID /home       btrfs $mount_opts,subvol=@home      0 0
UUID=$ROOT_UUID /var        btrfs $mount_opts,subvol=@var       0 0
UUID=$ROOT_UUID /var/log    btrfs $mount_opts,subvol=@log       0 0
UUID=$ROOT_UUID /.snapshots btrfs $mount_opts,subvol=@snapshots 0 0
UUID=$ESP_UUID  /boot/efi   vfat  umask=0077                    0 1
EOF

KVER="$(ls -1 "$MNT/lib/modules" 2>/dev/null | sort -V | tail -1 || true)"
[ -n "$KVER" ] || err "no kernel modules found in target (/lib/modules)"
if [ -n "${KERNEL:-}" ] && [ -f "$KERNEL" ]; then
  install -Dm644 "$KERNEL" "$MNT/boot/vmlinuz-$KVER"
fi
[ -f "$MNT/boot/vmlinuz-$KVER" ] || err "no kernel image at /boot/vmlinuz-$KVER"

log "regenerating initramfs ($KVER)"
chroot "$MNT" update-initramfs -c -k "$KVER"

CMDLINE="quiet"
[ "${SERIAL_CONSOLE:-0}" = 1 ] && CMDLINE="console=tty0 console=ttyS0,115200"
mkdir -p "$MNT/etc/default"
if [ -f "$MNT/etc/default/grub" ]; then
  sed -i 's|^GRUB_CMDLINE_LINUX_DEFAULT=.*|GRUB_CMDLINE_LINUX_DEFAULT="'"$CMDLINE"'"|' "$MNT/etc/default/grub"
else
  cat > "$MNT/etc/default/grub" <<EOF
GRUB_DEFAULT=0
GRUB_TIMEOUT=3
GRUB_DISTRIBUTOR="saltOS"
GRUB_CMDLINE_LINUX_DEFAULT="$CMDLINE"
GRUB_CMDLINE_LINUX=""
GRUB_TERMINAL="console serial"
GRUB_SERIAL_COMMAND="serial --speed=115200"
EOF
fi

log "installing GRUB (bios)"
chroot "$MNT" grub-install --target=i386-pc --recheck "$TARGET_DISK"
if [ "$efi" = 1 ]; then
  log "installing GRUB (efi)"
  chroot "$MNT" grub-install --target=x86_64-efi --efi-directory=/boot/efi \
    --bootloader-id=saltOS --recheck --removable || true
fi
log "generating grub.cfg"
chroot "$MNT" grub-mkconfig -o /boot/grub/grub.cfg

log "registering deployment with salt"
chroot "$MNT" salt deployments --register-current 2>/dev/null || true

log "syncing"
sync
log "saltOS installed to $TARGET_DISK"
