---
modules-search: [ local, /usr/lib/calamares/modules, /usr/lib/x86_64-linux-gnu/calamares/modules, /usr/lib/aarch64-linux-gnu/calamares/modules ]

instances:
- id: saltos_btrfs
  module: saltos_btrfs
  config: saltos_btrfs.conf
- id: saltos_runit
  module: saltos_runit
  config: saltos_runit.conf
- id: saltos_stratum
  module: saltos_stratum
  config: saltos_stratum.conf
- id: saltos_cleanup
  module: saltos_cleanup
  config: saltos_cleanup.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - saltos_btrfs
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - saltos_runit
  - saltos_stratum
  - saltos_cleanup
  - bootloader
  - grubcfg
  - packages
  - umount
- show:
  - finished

branding: saltos

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

hide-back-and-next-during-exec: true

quit-at-end: false
