---
modules-search: [ local, /usr/lib/calamares/modules, /usr/lib/x86_64-linux-gnu/calamares/modules, /usr/lib/aarch64-linux-gnu/calamares/modules ]

instances:
- id: stratum
  module: packagechooser
  config: packagechooser_stratum.conf
- id: desktop
  module: packagechooser
  config: packagechooser_desktop.conf
- id: saltos_setup
  module: saltos_setup
  config: saltos_setup.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - packagechooser@stratum
  - packagechooser@desktop
  - users
  - summary
- exec:
  - partition
  - mount
  - saltos_setup
  - umount
- show:
  - finished

branding: saltos

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

hide-back-and-next-during-exec: true

quit-at-end: false
