name = "lxqt-menu-data"
version = "2.1.0"
release = 1
summary = "LXQt menu files"
license = "LGPL-2.1-or-later"
arch = ["x86_64", "aarch64"]

[source]
url = "https://github.com/lxqt/lxqt-menu-data/releases/download/2.1.0/lxqt-menu-data-2.1.0.tar.xz"
sha256 = "d2d2187313c16fc435a7313e53b80ace7ccba0b5de6c0d9cd53bfdfa13d5eab4"

[build]
system = "cmake"
deps = ["cmake", "ninja", "pkgconf", "gcc", "lxqt-build-tools", "qt6-tools"]
script = """
#!/bin/sh
cmake -G Ninja -S "$SALT_SRC" -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_SYSCONFDIR=/etc
cmake --build build -j"$SALT_JOBS"
DESTDIR="$SALT_DEST" cmake --install build
"""

[package]
deps = []

[reproducibility]
status = "verified"
