---
efiBootLoader: "grub"
kernel: "/vmlinuz"
img: "/initrd.img"
fallback: "/initrd.img"

timeout: "5"
bootloaderEntryName: "saltOS"
kernelLine: ", with saltOS"
fallbackKernelLine: ", with saltOS (fallback)"

grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"

installEFIFallback: true
