---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512MiB
efiSystemPartitionName: EFI

userSwapChoices:
    - none
    - small

drawNestedPartitions: false
alwaysShowPartitionLabels: true
allowManualPartitioning: true

initialPartitioningChoice: erase
initialSwapChoice: none

defaultFileSystemType: "btrfs"
availableFileSystemTypes: [ "btrfs", "ext4" ]

enableLuksAutomatedPartitioning: false
