---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false
showDonateUrl: false
requirements:
    requiredStorage: 8
    requiredRam: 1.0
    internetCheckUrl: http://deb.debian.org
    check:
        - storage
        - ram
        - root
        - screen
        - internet
    required:
        - storage
        - ram
        - root
