name = "pango"
version = "1.54.0"
release = 1
summary = "Library for layout and rendering of internationalized text"
license = "LGPL-2.1-or-later"
arch = ["x86_64", "aarch64"]

[source]
url = "https://download.gnome.org/sources/pango/1.54/pango-1.54.0.tar.xz"
sha256 = "8a9eed75021ee734d7fc0fdf3a65c3bba51dfefe4ae51a9b414a60c70b2d1ed8"

[build]
system = "meson"
deps = ["meson", "ninja", "pkgconf", "gcc", "glib", "harfbuzz", "fontconfig", "freetype", "cairo"]

[package]
deps = ["glibc", "glib", "harfbuzz", "fontconfig", "freetype", "cairo"]

[reproducibility]
status = "verified"
