name = "libxinerama"
version = "1.1.5"
release = 1
summary = "X11 libXinerama library"
license = "MIT"
arch = ["x86_64", "aarch64"]

[source]
url = "https://www.x.org/releases/individual/lib/libXinerama-1.1.5.tar.xz"
sha256 = "5094d1f0fcc1828cb1696d0d39d9e866ae32520c54d01f618f1a3c1e30c2085c"

[build]
system = "autotools"
deps = ["pkgconf", "gcc", "make", "libx11", "libxext", "xorgproto"]
script = """
#!/bin/sh
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --disable-static
make -j"$SALT_JOBS"
make DESTDIR="$SALT_DEST" install
"""

[package]
deps = ["glibc", "libx11", "libxext"]

[reproducibility]
status = "verified"
