---
repo: /run/salt/repo

basePackages:
    - glibc
    - linux
    - runit
    - btrfs-progs
    - salt
    - dbus
    - eudev
    - seatd
    - dhcpcd
    - chrony
    - openssh
    - grub
    - efibootmgr

desktopPackages:
    - lxqt
    - sddm
    - pipewire
    - mpv
    - pcmanfm-qt
    - qterminal
    - featherpad
    - helium

installDesktop: true
