name = "efivar"
version = "39"
release = 1
summary = "Library and tools to manipulate UEFI variables"
license = "LGPL-2.1-or-later"
arch = ["x86_64", "aarch64"]

[source]
url = "https://github.com/rhboot/efivar/archive/refs/tags/39.tar.gz"
sha256 = "c9edd15f2eeeea63232f3e669a48e992c7be9aff57ee22672ac31f5eca1609a6"

[build]
system = "make"
deps = ["gcc", "make", "pkgconf"]
script = """
#!/bin/sh
make -j"$SALT_JOBS"
make DESTDIR="$SALT_DEST" libdir=/usr/lib bindir=/usr/bin install
"""

[package]
deps = ["glibc"]

[reproducibility]
status = "verified"
