name = "libxdmcp"
version = "1.1.5"
release = 1
summary = "X11 libXdmcp library"
license = "MIT"
arch = ["x86_64", "aarch64"]

[source]
url = "https://www.x.org/releases/individual/lib/libXdmcp-1.1.5.tar.xz"
sha256 = "d8a5222828c3adab70adf69a5583f1d32eb5ece04304f7f8392b6a353aa2228c"

[build]
system = "autotools"
deps = ["pkgconf", "gcc", "make", "xorgproto"]
script = """
#!/bin/sh
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --disable-static
make -j"$SALT_JOBS"
make DESTDIR="$SALT_DEST" install
"""

[package]
deps = ["glibc"]

[reproducibility]
status = "verified"
