---
efiDirectory: /boot/efi
bootloaderId: saltOS
distributor: saltOS
grubInstall: grub-install
grubMkconfig: grub-mkconfig
grubCfg: /boot/grub/grub.cfg
efiTargets:
    x86_64: x86_64-efi
    aarch64: arm64-efi
biosTarget: i386-pc
