#!/bin/bash

palette=(1a1b26 f7768e 9ece6a e0af68 7aa2f7 bb9af7 7dcfff a9b1d6 414868 f7768e 9ece6a e0af68 7aa2f7 bb9af7 7dcfff c0caf5)

if [ -t 1 ] && [ "$TERM" = "linux" ]; then
  for i in "${!palette[@]}"; do
    printf '\e]P%X%s' "$i" "${palette[$i]}"
  done
  printf '\e[8]'
fi
printf '\e[?25l'
clear
