---
subvolumes:
    "@": /
    "@home": /home
    "@var": /var
    "@log": /var/log
    "@snapshots": /.snapshots

mountOptions: "rw,noatime,compress=zstd:1,space_cache=v2"
mountOptionsSsd: "rw,noatime,compress=zstd:1,ssd,space_cache=v2,discard=async"
