#!/bin/sh
exec 2>&1
if [ ! -e /run/live-setup.done ]; then
	/usr/lib/saltos/live-setup.sh
	touch /run/live-setup.done
fi
sv check /etc/runit/runsvdir/current/udevd >/dev/null 2>&1
exec sleep infinity
