---
liveUser: salt

gettys:
    - agetty-tty1
    - agetty-tty2

removeServices:
    - boot-check
    - desktop-check
    - installer-check
    - stratum-e2e
    - agetty-serial
    - netdhcp

sudoersDrops:
    - salt
    - calamares

removeFromHome:
    - .bash_profile
    - .xsession-errors
    - Desktop/Install-saltOS.desktop

removeLiveUser: true
