---
runsvdir: /etc/runit/runsvdir/current

authoritative: true

enable:
    - udevd
    - dbus
    - seatd
    - socklog
    - dhcpcd
    - chronyd
    - sddm
    - agetty-tty1
    - agetty-tty2

disable:
    - sshd
