theme = "catppuccin"
license = "Unsplash License (https://unsplash.com/license)"

[[wallpaper]]
id = "YhpiG-0mKUg"
title = "Purple nebula"
photographer = "Marek Pavlík"
profile = "https://unsplash.com/@marpicek"
page = "https://unsplash.com/photos/YhpiG-0mKUg"
url = "https://images.unsplash.com/photo-1754851539824-5a87c5c7cb86?fm=jpg&q=85&w=3840&fit=max"
sha256 = "0a94247e3bfa4276926757646ddbc19c6732aeca176043773445a476665dbe38"

[[wallpaper]]
id = "-Of-1FQHiA4"
title = "Amethyst crystals"
photographer = "Calvin Chai"
profile = "https://unsplash.com/@calvin_chai"
page = "https://unsplash.com/photos/-Of-1FQHiA4"
url = "https://images.unsplash.com/photo-1609216970378-ce61cd74a187?fm=jpg&q=85&w=3840&fit=max"
sha256 = "ecbdbb8023df45a8c0f38206840c38a53c1ab0c7ce1e8e62c190bd8ab641ead5"

[[wallpaper]]
id = "GvPgFYz4niM"
title = "Charoite mineral, macro"
photographer = "Elliot Cullen"
profile = "https://unsplash.com/@elliot_c"
page = "https://unsplash.com/photos/GvPgFYz4niM"
url = "https://images.unsplash.com/photo-1632805364446-6baf3e3bb21d?fm=jpg&q=85&w=3840&fit=max"
sha256 = "83ba6d6ae8cf35167cb753e36bd6f9d2035db1d112b3644921b86de113bc7f02"
