theme = "gruvbox"
license = "Unsplash License (https://unsplash.com/license)"

[[wallpaper]]
id = "z061ROXh7no"
title = "Salt piles and windmill at sunset"
photographer = "Marco Grosso"
profile = "https://unsplash.com/@marcozzolo90"
page = "https://unsplash.com/photos/z061ROXh7no"
url = "https://images.unsplash.com/photo-1764377975946-1649b873b306?fm=jpg&q=85&w=3840&fit=max"
sha256 = "97dc1a3d195e9f7d165f0d84971cb37fe72f7f7862bf42671044dc23c733c4f5"

[[wallpaper]]
id = "SjO_AQDU6yA"
title = "Golden sand dunes illuminated by a dramatic sunset"
photographer = "Edwin Rodriguez"
profile = "https://unsplash.com/@ed_757"
page = "https://unsplash.com/photos/SjO_AQDU6yA"
url = "https://images.unsplash.com/photo-1768207750855-f72a8da13552?fm=jpg&q=85&w=3840&fit=max"
sha256 = "bd50ac0eae204862700726c3b9d65d451679a701890702dfdadff04a4ae5f9cc"

[[wallpaper]]
id = "4GsUAuZbSVc"
title = "Eroded red sandstone"
photographer = "Haci"
profile = "https://unsplash.com/@e_haci"
page = "https://unsplash.com/photos/4GsUAuZbSVc"
url = "https://images.unsplash.com/photo-1775239560234-a7f57a6e4e06?fm=jpg&q=85&w=3840&fit=max"
sha256 = "33092cfc8c5d096333c741a63f03298abf59436849d88b9c79941c56009f4945"
